### ISSUE TITLE
Incorrect statics saved at the end of the game

### ISSUE THREAD

**Issue by masonlee0622** [garlinhs/game-2048#2]
After I finish a game, the final statistics displayed and stored do not match my final score. The final score is always stored as 0, and the largest tile is always stored as 2. Number of moves is always stored as -1. Time taken is stored correctly.

To recreate this error:
Clone the git repo, install it to a local prefix, run the game, select a new game, and succeed in a game.

![image](https://github.com/garlinhs/game-2048/assets/131757114/4363d427-9b08-46d1-8dc3-3585ee72effe)

**Comment by garlinhs** [comment]
@masonlee0622 Fixed this issue.
